AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Guardfile

Style/Documentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/ClassAndModuleChildren:
  Enabled: false
