# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02dd531a129973461fe705540d2e2856fd4159431aded04a5d1d00379d7b686a535922dabfbcec3a2b04817499c908882809c84095277a373f360d54aaa95614
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  tawk_app_id: <%= ENV["TAWK_APP_ID"] %>
  jwplayer: <%= ENV["JWPLAYER"] %>
  authorize_net_login: <%= ENV["AUTHORIZE_NET_LOGIN"] %>
  authorize_net_transaction_key: <%= ENV["AUTHORIZE_NET_TRANSACTION_KEY"] %>
  authorize_net_merchant_hash: <%= ENV["AUTHORIZE_NET_MERCHANT_HASH"] %>
  pp_submit_url: <%= ENV["PP_SUBMIT_URL"] %>
  pp_callback_url: <%= ENV["PP_CALLBACK_URL"] %>
  pp_merchant_id: <%= ENV["PP_MERCHANT_ID"] %>

test:
  secret_key_base: 0a9f1395308014808bb73ca3ad01580d74f2dd1f25e9599a10978390e75028d32179500aa5771a237c3626df56a23a23d7b373b04779190a92bf6bdc005b5dc7
  facebook_app_id: "FACEBOOK_APP_ID"
  facebook_secret: "FACEBOOK_SECRET"
  google_app_id: "GOOGLE_APP_ID"
  tawk_app_id: "TAWK_APP_ID"
  jwplayer: "JWPLAYER"
  authorize_net_login: "AUTHORIZE_NET_LOGIN"
  authorize_net_transaction_key: "AUTHORIZE_NET_TRANSACTION_KEY"
  authorize_net_merchant_hash: "AUTHORIZE_NET_MERCHANT_HASH"
  pp_submit_url: "PP_SUBMIT_URL"
  pp_callback_url: "PP_CALLBACK_URL"
  pp_merchant_id: "PP_MERCHANT_ID"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  tawk_app_id: <%= ENV["TAWK_APP_ID"] %>
  jwplayer: <%= ENV["JWPLAYER"] %>
  authorize_net_login: <%= ENV["AUTHORIZE_NET_LOGIN"] %>
  authorize_net_transaction_key: <%= ENV["AUTHORIZE_NET_TRANSACTION_KEY"] %>
  authorize_net_merchant_hash: <%= ENV["AUTHORIZE_NET_MERCHANT_HASH"] %>
  pp_submit_url: <%= ENV["PP_SUBMIT_URL"] %>
  pp_callback_url: <%= ENV["PP_CALLBACK_URL"] %>
  pp_merchant_id: <%= ENV["PP_MERCHANT_ID"] %>
