source "https://rubygems.org"

gem "bundler", "< 1.18"

gem "rails", "~> 4.2.11.1"

gem "slim-rails"

gem "countries", "~> 3.0", require: false
gem "sprockets-rails", "~> 2.3.3"

gem "bigdecimal", "1.4.2"

gem "active_model_serializers", "~> 0.9.0", path: "vendor/gems/active_model_serializers-0-9-stable"
gem "bcrypt"
gem "faraday", "~> 1.0.1"
gem "jwt", "~> 2.3.0"
gem "pundit", "~> 1.1.0"
gem "virtus", "~> 1.0.4"

# Billing
gem "authorizenet", "~> 1.9.4", require: false
gem "paypal-sdk-core", "~> 0.3.1", require: false

# Facebook
gem "koala", "~> 2.2.0", require: false
gem "public_suffix", "~> 3.0.3", require: false

# Google
gem 'googleauth', require: false

# Events
gem "wisper", "~> 2.0.0.rc1"
gem "wisper-activejob", "~> 0.0.2"

# Write to AWS
gem "aws-sdk", "~> 2.0", require: false

# Feature flip
gem "ruby_flipper"

# Cache action response
gem "actionpack-action_caching", "~> 1.1.1"

gem "dalli"
gem "puma", "~> 4.3.3"
gem "redis-rails", "~> 4.0.0"

gem "nokogiri", "<= 1.9.1"
gem "oj", "~> 3.7.8"
gem "url_tokenizer", "~> 1.7.0"

group :production do
  gem "pg", "~> 0.18"
  gem "rack-attack", "~> 5.4.0"
  gem "sidekiq", "~> 4.1.0"
  gem "sidekiq-failures", "~> 0.4.5"
  gem "sidetiq", "~> 0.7.0"
  gem "sinatra"
end

group :production, :development do
  gem "uglifier", ">= 4.1.15"

  # ENGINES

  # Web interface
  gem "web_client", git: "git@github.com:malimar-tv/web_client.git", branch: "production"
  # gem 'web_client', path: '../web_client'

  # ActiveAdmin
  gem "active_admin_theme"
  gem "activeadmin", "~> 1.2.1"
  gem "arbre", "1.1.1" # TODO: update once upgrade ruby
  gem "chosen-rails"
  gem "country_select", require: false
  gem "google_visualr"
  gem "inherited_resources", "~> 1.8.0"

  # Documentation
  gem "apitome", "0.3.0"
end

group :production, :test do
  gem "rollbar", "~> 2.11.3"
end

unless ENV["RACK_ENV"] == "production"
  group :migration, :test do
    gem "processor"
    gem "recurly"
    gem "thor"
  end

  group :development, :test do
    gem "dotenv-rails"
    gem "rspec-rails", "~> 3.4.0"
    gem "rspec-retry"
    gem "rspec_api_documentation", "~> 4.8.0"
    gem "spring"
    gem "spring-commands-rspec"

    # Call 'byebug' anywhere in the code to stop execution and get a debugger console
    gem "pry-rails"
    gem "sqlite3", "~> 1.3.6"
  end

  group :development do
    gem "guard-livereload", "~> 2.4", require: false
    gem "parallel_tests"
    gem "rack-livereload"
  end

  group :test do
    gem "email_spec", require: false
    gem "factory_girl", "~> 4.7.0"
    gem "faker"
    gem "vcr", github: "vcr/vcr"
    gem "webmock"
    gem "wisper-rspec", require: false
    # FIXME: remove when on Rails 5
    gem "test_after_commit"
  end
end
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
